# Generated by Django 5.2 on 2025-04-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО руководителя')),
                ('mobile_phone', models.CharField(max_length=20, verbose_name='Мобильный телефон')),
                ('other_contact', models.CharField(blank=True, max_length=200, verbose_name='Другой способ связи')),
            ],
            options={
                'verbose_name': 'Руководитель',
                'verbose_name_plural': 'Руководители',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст варианта')),
            ],
            options={
                'verbose_name': 'Вариант выбора',
                'verbose_name_plural': 'Варианты выбора',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Фамилия, имя')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('school', models.CharField(max_length=100, verbose_name='Школа')),
                ('grade', models.CharField(max_length=10, verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('adg', 'Республика Адыгея'), ('alt', 'Алтайский край'), ('amr', 'Амурская область'), ('ark', 'Архангельская область'), ('ast', 'Астраханская область'), ('bel', 'Белгородская область'), ('bry', 'Брянская область'), ('vld', 'Владимирская область'), ('vlg', 'Волгоградская область'), ('volog', 'Вологодская область'), ('vor', 'Воронежская область'), ('iva', 'Ивановская область'), ('irk', 'Иркутская область'), ('kbd', 'Кабардино-Балкарская Республика'), ('kln', 'Калининградская область'), ('klg', 'Калужская область'), ('kam', 'Камчатский край'), ('kar', 'Карачаево-Черкесская Республика'), ('kem', 'Кемеровская область'), ('kir', 'Кировская область'), ('kos', 'Костромская область'), ('kras', 'Краснодарский край'), ('krs', 'Красноярский край'), ('kur', 'Курганская область'), ('kursk', 'Курская область'), ('len', 'Ленинградская область'), ('lip', 'Липецкая область'), ('mag', 'Магаданская область'), ('mow', 'Московская область'), ('mur', 'Мурманская область'), ('niz', 'Нижегородская область'), ('nvg', 'Новгородская область'), ('nsk', 'Новосибирская область'), ('oms', 'Омская область'), ('orb', 'Оренбургская область'), ('orl', 'Орловская область'), ('pen', 'Пензенская область'), ('perm', 'Пермский край'), ('pri', 'Приморский край'), ('psk', 'Псковская область'), ('ros', 'Ростовская область'), ('rya', 'Рязанская область'), ('sam', 'Самарская область'), ('sar', 'Саратовская область'), ('sak', 'Сахалинская область'), ('svl', 'Свердловская область'), ('smo', 'Смоленская область'), ('tamb', 'Тамбовская область'), ('tver', 'Тверская область'), ('tom', 'Томская область'), ('tul', 'Тульская область'), ('tyu', 'Тюменская область'), ('udm', 'Удмуртская Республика'), ('uly', 'Ульяновская область'), ('khab', 'Хабаровский край'), ('khak', 'Республика Хакасия'), ('khm', 'Ханты-Мансийский автономный округ'), ('chel', 'Челябинская область'), ('che', 'Чеченская Республика'), ('chu', 'Чувашская Республика'), ('chuk', 'Чукотский автономный округ'), ('yan', 'Ямало-Ненецкий автономный округ'), ('yar', 'Ярославская область'), ('sev', 'Севастополь'), ('krm', 'Республика Крым'), ('msc', 'Москва'), ('spb', 'Санкт-Петербург'), ('ynk', 'Республика Тыва (Тува)'), ('dag', 'Республика Дагестан'), ('ing', 'Республика Ингушетия'), ('kalm', 'Республика Калмыкия'), ('mrd', 'Республика Мордовия'), ('sah', 'Республика Саха (Якутия)'), ('tatar', 'Республика Татарстан'), ('bur', 'Республика Бурятия'), ('altres', 'Республика Алтай'), ('zab', 'Забайкальский край'), ('sta', 'Ставропольский край'), ('kmr', 'Республика Коми'), ('nnao', 'Ненецкий автономный округ'), ('amu', 'Республика Марий Эл')], max_length=10, verbose_name='Регион')),
                ('city', models.CharField(max_length=100, verbose_name='Населенный пункт')),
                ('organization_name', models.CharField(max_length=200, verbose_name='Название организации')),
                ('postal_address', models.CharField(max_length=200, verbose_name='Почтовый адрес')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон с кодом города')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Сайт (необязательно)')),
                ('comment', models.CharField(max_length=500, verbose_name='Комментарий')),
                ('leaders', models.ManyToManyField(blank=True, to='users.leader', verbose_name='Руководители')),
                ('options', models.ManyToManyField(blank=True, to='users.option', verbose_name='Выбранные варианты')),
                ('participants', models.ManyToManyField(blank=True, to='users.participant', verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
