# Generated by Django 5.2 on 2025-07-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='age',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='project',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='school',
        ),
        migrations.AddField(
            model_name='application',
            name='nomination',
            field=models.CharField(blank=True, choices=[('1', 'НОМИНАЦИЯ № 1. «ПРОБЛЕМЫ ПРИРОДНЫХ ЭКОСИСТЕМ»'), ('2', 'НОМИНАЦИЯ № 2. «ЖИВОТНЫЕ И РАСТЕНИЯ В ЭКОСИСТЕМАХ»'), ('3', 'НОМИНАЦИЯ № 3. «ЭТНОГРАФИЧЕСКИЕ ИССЛЕДОВАНИЯ»'), ('4', 'НОМИНАЦИЯ № 4. «ЭКОЛОГИЧЕСКИЕ ПРОБЛЕМЫ ПОСЕЛЕНИЙ.ПРОБЛЕМЫ ЭКОНОМИИ ЭНЕРГИИ И РЕСУРСОВ»'), ('5', 'НОМИНАЦИЯ № 5. «ЭКОТЕХ: ТЕХНОЛОГИИ ВО БЛАГО ПРИРОДЫ»'), ('6', 'НОМИНАЦИЯ № 6. «ПЕРВЫЕ ШАГИ В ЭКОЛОГИИ»')], max_length=1, null=True, verbose_name='Номинация'),
        ),
        migrations.AddField(
            model_name='application',
            name='project_title',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Тема проекта'),
        ),
        migrations.AddField(
            model_name='application',
            name='registration_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Регистрационный номер'),
        ),
        migrations.AddField(
            model_name='participant',
            name='college_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Колледж/ВУЗ'),
        ),
        migrations.AddField(
            model_name='participant',
            name='course',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='participant',
            name='family_education_surname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фамилия (для семейного воспитания)'),
        ),
        migrations.AddField(
            model_name='participant',
            name='family_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название семейного коллектива (фамилия)'),
        ),
        migrations.AddField(
            model_name='participant',
            name='kindergarten_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Детский сад'),
        ),
        migrations.AddField(
            model_name='participant',
            name='movement_type',
            field=models.CharField(blank=True, choices=[('children', 'Детское'), ('youth', 'Молодежное')], max_length=20, null=True, verbose_name='Тип движения'),
        ),
        migrations.AddField(
            model_name='participant',
            name='participation_type',
            field=models.CharField(choices=[('school', 'Школа'), ('college', 'Колледж/ВУЗ'), ('additional', 'Учреждение ДО'), ('family', 'Семейный коллектив'), ('movement', 'Движение'), ('kindergarten', 'Детский сад'), ('family_education', 'Семейное воспитание')], default='', max_length=20, verbose_name='Тип участия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='school_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='application',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='application',
            name='region',
            field=models.CharField(max_length=100, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='additional_education_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Учреждение ДО'),
        ),
    ]
