# Generated by Django 5.2 on 2025-04-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_application_options_delete_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='project',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тема проекта'),
        ),
    ]
