# Generated by Django 5.2 on 2025-04-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_participant_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='academic_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ученое звание'),
        ),
        migrations.AddField(
            model_name='leader',
            name='position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='leader',
            name='workplace',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Место работы'),
        ),
    ]
