# Generated by Django 5.2 on 2025-04-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_leader_academic_title_leader_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='additional_education_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Наименование учреждения'),
        ),
        migrations.AddField(
            model_name='participant',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Школа'),
        ),
    ]
