# Generated by Django 5.2 on 2025-04-02 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_slide_alter_news_content_alter_news_publication_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_images/')),
                ('alt_text', models.CharField(blank=True, max_length=200, null=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.news')),
            ],
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
