# Generated by Django 5.2 on 2025-04-02 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_newsimage_delete_slide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsImage',
        ),
    ]
